{% set name = "reserver" %}
{% set version = "0.5" %}

package:
    name: {{ name|lower }}
    version: {{ version }}
source:
    git_url: https://github.com/openscilab/reserver
    git_rev: v{{ version }}
build:
    noarch: python
    number: 0
    script: {{ PYTHON }} -m pip install . -vv
requirements:
    host:
        - pip
        - setuptools
        - python >=3.7
    run:
        - python >=3.7
about:
    home: https://github.com/openscilab/reserver
    license: MIT
    license_family: MIT
    summary: Python library for PyPI package name reservation 
    description: |
        Reserver is an open source Python package that easily reserves PyPI package name.
        
        Website: https://openscilab.com

        Repo: https://github.com/openscilab/reserver
extra:
    recipe-maintainers:
        - AHReccese
